/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;

import java.awt.TextField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;


public class Restaurant extends javax.swing.JFrame {
  int total;
    int  lbldosa,lblpaav,lbltea,lblvada,lblnoodle,lblmilk,lblcofee,lbllemonade,lblcf,lblcd,lblmfd;
    double lbltax,lblsubtotal,lbltotal;
    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
        
      pan_recipt.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_print_output = new javax.swing.JLabel();
        pan_head = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_myname = new javax.swing.JLabel();
        pan_l1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_f_dosa = new javax.swing.JLabel();
        lbl_f_paav = new javax.swing.JLabel();
        lbl_f_vada = new javax.swing.JLabel();
        lbl_f_noodle = new javax.swing.JLabel();
        tf_f_vada = new javax.swing.JTextField();
        tf_f_paav = new javax.swing.JTextField();
        tf_f_noodle = new javax.swing.JTextField();
        tf_f_dosa = new javax.swing.JTextField();
        pan_r1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_d_cofee = new javax.swing.JLabel();
        lbl_d_tea = new javax.swing.JLabel();
        lbl_d_milk = new javax.swing.JLabel();
        lbl_d_lemonade = new javax.swing.JLabel();
        tf_d_tea = new javax.swing.JTextField();
        tf_d_milk = new javax.swing.JTextField();
        tf_d_cofee = new javax.swing.JTextField();
        tf_d_lemonade = new javax.swing.JTextField();
        pan_recipt = new javax.swing.JPanel();
        lbl_print_name = new javax.swing.JLabel();
        lbl_recipt = new javax.swing.JLabel();
        lbl_r_cf = new javax.swing.JLabel();
        lbl_r_cf_amount = new javax.swing.JLabel();
        lbl_r_cd_amount = new javax.swing.JLabel();
        lbl_r_mfd_amount = new javax.swing.JLabel();
        lbl_r_cf1 = new javax.swing.JLabel();
        lbl_r_cf2 = new javax.swing.JLabel();
        lbl_r_cf3 = new javax.swing.JLabel();
        lbl_r_cf4 = new javax.swing.JLabel();
        lbl_r_cf5 = new javax.swing.JLabel();
        lbl_r_cf6 = new javax.swing.JLabel();
        lbl_r_subtotal = new javax.swing.JLabel();
        lbl_r_tax = new javax.swing.JLabel();
        lbl_r_total = new javax.swing.JLabel();
        lbl_r_billno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pan_l2 = new javax.swing.JPanel();
        lbl_cd = new javax.swing.JLabel();
        lbl_cf = new javax.swing.JLabel();
        lbl_ct = new javax.swing.JLabel();
        tf_cd = new javax.swing.JTextField();
        tf_ct = new javax.swing.JTextField();
        tf_cf = new javax.swing.JTextField();
        pan_r2 = new javax.swing.JPanel();
        lbl_tax = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        tf_tax = new javax.swing.JTextField();
        tf_total = new javax.swing.JTextField();
        tf_subtotal = new javax.swing.JTextField();
        pan_total = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_total = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lbl_print_output.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_head.setBackground(new java.awt.Color(72, 70, 70));
        pan_head.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_head.setForeground(new java.awt.Color(255, 255, 255));

        lbl_name.setBackground(new java.awt.Color(255, 102, 51));
        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Restaurant Management Software");

        lbl_myname.setFont(new java.awt.Font("Rage Italic", 2, 36)); // NOI18N
        lbl_myname.setForeground(new java.awt.Color(255, 102, 0));
        lbl_myname.setText("By -Padmanabh Wattamwar");

        javax.swing.GroupLayout pan_headLayout = new javax.swing.GroupLayout(pan_head);
        pan_head.setLayout(pan_headLayout);
        pan_headLayout.setHorizontalGroup(
            pan_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 1416, Short.MAX_VALUE)
            .addGroup(pan_headLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_myname, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pan_headLayout.setVerticalGroup(
            pan_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_headLayout.createSequentialGroup()
                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_myname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pan_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1420, 140));

        pan_l1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Food");

        lbl_f_dosa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_f_dosa.setText("Dosa");

        lbl_f_paav.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_f_paav.setText("Paav Bhaji");

        lbl_f_vada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_f_vada.setText("Vada Sambar");

        lbl_f_noodle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_f_noodle.setText("Noodles");

        tf_f_vada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_f_vada.setText("0");

        tf_f_paav.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_f_paav.setText("0");
        tf_f_paav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_f_paavActionPerformed(evt);
            }
        });

        tf_f_noodle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_f_noodle.setText("0");

        tf_f_dosa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_f_dosa.setText("0");

        javax.swing.GroupLayout pan_l1Layout = new javax.swing.GroupLayout(pan_l1);
        pan_l1.setLayout(pan_l1Layout);
        pan_l1Layout.setHorizontalGroup(
            pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_l1Layout.createSequentialGroup()
                .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_l1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_l1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan_l1Layout.createSequentialGroup()
                                .addComponent(lbl_f_noodle, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_f_noodle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_l1Layout.createSequentialGroup()
                                .addComponent(lbl_f_vada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_f_vada, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_l1Layout.createSequentialGroup()
                                .addComponent(lbl_f_paav, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(tf_f_paav, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_l1Layout.createSequentialGroup()
                                .addComponent(lbl_f_dosa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(tf_f_dosa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pan_l1Layout.setVerticalGroup(
            pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_l1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_f_paav, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f_paav, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_f_dosa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f_dosa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_f_vada, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f_vada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_f_noodle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_f_noodle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(pan_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 490, 340));

        pan_r1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Drinks");

        lbl_d_cofee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_d_cofee.setText("Cofee");

        lbl_d_tea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_d_tea.setText("Tea");

        lbl_d_milk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_d_milk.setText("MIlk");

        lbl_d_lemonade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_d_lemonade.setText("Lemonade");

        tf_d_tea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_d_tea.setText("0");

        tf_d_milk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_d_milk.setText("0");

        tf_d_cofee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_d_cofee.setText("0");

        tf_d_lemonade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_d_lemonade.setText("0");

        javax.swing.GroupLayout pan_r1Layout = new javax.swing.GroupLayout(pan_r1);
        pan_r1.setLayout(pan_r1Layout);
        pan_r1Layout.setHorizontalGroup(
            pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_r1Layout.createSequentialGroup()
                .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_r1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(pan_r1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_d_lemonade, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(lbl_d_cofee, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_d_tea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_d_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_d_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_d_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_d_cofee, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_d_lemonade, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        pan_r1Layout.setVerticalGroup(
            pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_r1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_d_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_d_tea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_d_cofee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_d_cofee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_d_lemonade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_d_lemonade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_r1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_d_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_d_milk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(pan_r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 450, 340));

        pan_recipt.setBackground(new java.awt.Color(255, 255, 255));
        pan_recipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_print_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_print_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_print_name.setText("Billing Management Software");

        lbl_recipt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_recipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_recipt.setText("Recipt");

        lbl_r_cf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf.setText("Cost  Of Food");

        lbl_r_cf_amount.setText("jLabel1");

        lbl_r_cd_amount.setText("jLabel1");

        lbl_r_mfd_amount.setText("jLabel1");

        lbl_r_cf1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf1.setText("Cost Of Drinks");

        lbl_r_cf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_r_cf2.setText("========================================");

        lbl_r_cf3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf3.setText("Sub Total");

        lbl_r_cf4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf4.setText("Cost Of Meal");

        lbl_r_cf5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf5.setText("Tax");

        lbl_r_cf6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_r_cf6.setText("Total");

        lbl_r_subtotal.setText("jLabel1");

        lbl_r_tax.setText("jLabel1");

        lbl_r_total.setText("jLabel1");

        lbl_r_billno.setText("Bill No");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Authorised Signature");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(Padmanabh D. Wattamwar)");

        javax.swing.GroupLayout pan_reciptLayout = new javax.swing.GroupLayout(pan_recipt);
        pan_recipt.setLayout(pan_reciptLayout);
        pan_reciptLayout.setHorizontalGroup(
            pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_reciptLayout.createSequentialGroup()
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_reciptLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_recipt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_r_billno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(pan_reciptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_print_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pan_reciptLayout.createSequentialGroup()
                                .addComponent(lbl_r_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(lbl_r_cf_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_reciptLayout.createSequentialGroup()
                                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_r_cf1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(lbl_r_cf4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_r_cd_amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(lbl_r_mfd_amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lbl_r_cf2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pan_reciptLayout.createSequentialGroup()
                                .addComponent(lbl_r_cf5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(lbl_r_tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pan_reciptLayout.createSequentialGroup()
                                .addComponent(lbl_r_cf3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(lbl_r_subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pan_reciptLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_r_cf6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(lbl_r_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_reciptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pan_reciptLayout.setVerticalGroup(
            pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_reciptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_print_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_recipt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_billno))
                .addGap(18, 18, 18)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_r_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_cf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_r_cd_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_cf1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_reciptLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_r_mfd_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_reciptLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_r_cf4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_r_cf2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_r_cf5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_r_cf3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_reciptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_r_cf6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_r_total, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(pan_recipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 410, 670));

        pan_l2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_cd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cd.setText("Cost of drinks");

        lbl_cf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cf.setText("Cost of food");

        lbl_ct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ct.setText("Cost of total items");

        tf_cd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_cd.setText("0");

        tf_ct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_ct.setText("0");

        tf_cf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_cf.setText("0");

        javax.swing.GroupLayout pan_l2Layout = new javax.swing.GroupLayout(pan_l2);
        pan_l2.setLayout(pan_l2Layout);
        pan_l2Layout.setHorizontalGroup(
            pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_l2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        pan_l2Layout.setVerticalGroup(
            pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_l2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pan_l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 490, 170));

        pan_r2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_tax.setText("Tax");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total.setText("Total");

        lbl_subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_subtotal.setText("Subtotal");

        tf_tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_tax.setText("0");

        tf_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_total.setText("0");
        tf_total.setToolTipText("");

        tf_subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_subtotal.setText("0");

        javax.swing.GroupLayout pan_r2Layout = new javax.swing.GroupLayout(pan_r2);
        pan_r2.setLayout(pan_r2Layout);
        pan_r2Layout.setHorizontalGroup(
            pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_r2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pan_r2Layout.setVerticalGroup(
            pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_r2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_r2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(pan_r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 450, 170));

        pan_total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_reset.setFont(btn_reset.getFont().deriveFont(btn_reset.getFont().getStyle() | java.awt.Font.BOLD, btn_reset.getFont().getSize()+5));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_total.setText("Total");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_totalLayout = new javax.swing.GroupLayout(pan_total);
        pan_total.setLayout(pan_totalLayout);
        pan_totalLayout.setHorizontalGroup(
            pan_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_totalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        pan_totalLayout.setVerticalGroup(
            pan_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_totalLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pan_totalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(pan_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
    int pav,dosa,vada,noodle,cdtotal,cftotal,tea,cofee,lemonade,milk;
    double tax ,subtotal;
    pav=50*Integer.parseInt(tf_f_paav.getText());
    dosa=40*Integer.parseInt(tf_f_dosa.getText());
    vada=45*Integer.parseInt(tf_f_vada.getText());
    noodle=30*Integer.parseInt(tf_f_noodle.getText());
    cftotal=vada+pav+noodle+dosa;
    tea=5*Integer.parseInt(tf_d_tea.getText());
    cofee=7*Integer.parseInt(tf_d_cofee.getText());
    lemonade=5*Integer.parseInt(tf_d_lemonade.getText());
    milk=8*Integer.parseInt(tf_d_milk.getText());
    cdtotal=milk+lemonade+cofee+tea;
    total=cdtotal+cftotal;
          
     tax = (total*10)/100;
     subtotal= (total*90)/100;    
     tf_total.setText(String.valueOf(total));

     tf_tax.setText(String.valueOf(tax));
     tf_subtotal.setText(String.valueOf(subtotal));
     tf_cd.setText(String.valueOf(cdtotal));
     tf_cf.setText(String.valueOf(cftotal));
     tf_ct.setText(String.valueOf(total));
     
 
    
    }//GEN-LAST:event_btn_totalActionPerformed

    private void tf_f_paavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_f_paavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_f_paavActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tf_f_vada.setText(null);
        tf_f_dosa.setText(null);
        tf_f_paav.setText(null);
        tf_f_noodle.setText(null);
        tf_d_tea.setText(null);
        tf_d_milk.setText(null);
        tf_d_lemonade.setText(null);
        tf_d_cofee.setText(null);
        tf_cd.setText(null);
        tf_cd.setText(null);
        tf_ct.setText(null);
        tf_total.setText(null);
        tf_tax.setText(null);
        tf_subtotal.setText(null);
        tf_total.setText(null);
        


    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        pan_recipt.setVisible(true);
        int a = 10+ (int)(Math.random()*1234);
        lbldosa=40*Integer.parseInt(tf_f_dosa.getText());
        lblpaav=50*Integer.parseInt(tf_f_paav.getText());
        lblvada=45*Integer.parseInt(tf_f_vada.getText());
        lblnoodle=30*Integer.parseInt(tf_f_noodle.getText());
        lbltea=5*Integer.parseInt(tf_d_tea.getText());
        lblcofee=7*Integer.parseInt(tf_d_cofee.getText());
        lblmilk=5*Integer.parseInt(tf_d_milk.getText());
        lbllemonade=8*Integer.parseInt(tf_d_lemonade.getText());
        lblcf=lbldosa+lblpaav+lblvada+lblnoodle;
        lblcd=+lbltea+lblmilk+lblcofee+lbllemonade;
        lblmfd=lblcd+lblcf;
        lbltax=(double)((lblmfd*10)/100);
        lblsubtotal=(double)((lblmfd*90)/100);
        lbltotal=lbltax+lblsubtotal;
       lbl_r_cf_amount.setText(String.valueOf(lblcf));
       lbl_r_cd_amount.setText(String.valueOf(lblcd));
       lbl_r_mfd_amount.setText(String.valueOf(lblmfd));
       lbl_r_tax.setText(String.valueOf(lbltax));
       lbl_r_subtotal.setText(String.valueOf(lblsubtotal));
       lbl_r_total.setText(String.valueOf(lbltotal));
       lbl_r_billno.setText("Bill No." + a );
       
       
       
       
       
    }//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_total;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_cd;
    private javax.swing.JLabel lbl_cf;
    private javax.swing.JLabel lbl_ct;
    private javax.swing.JLabel lbl_d_cofee;
    private javax.swing.JLabel lbl_d_lemonade;
    private javax.swing.JLabel lbl_d_milk;
    private javax.swing.JLabel lbl_d_tea;
    private javax.swing.JLabel lbl_f_dosa;
    private javax.swing.JLabel lbl_f_noodle;
    private javax.swing.JLabel lbl_f_paav;
    private javax.swing.JLabel lbl_f_vada;
    private javax.swing.JLabel lbl_myname;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_print_name;
    private javax.swing.JLabel lbl_print_output;
    private javax.swing.JLabel lbl_r_billno;
    private javax.swing.JLabel lbl_r_cd_amount;
    private javax.swing.JLabel lbl_r_cf;
    private javax.swing.JLabel lbl_r_cf1;
    private javax.swing.JLabel lbl_r_cf2;
    private javax.swing.JLabel lbl_r_cf3;
    private javax.swing.JLabel lbl_r_cf4;
    private javax.swing.JLabel lbl_r_cf5;
    private javax.swing.JLabel lbl_r_cf6;
    private javax.swing.JLabel lbl_r_cf_amount;
    private javax.swing.JLabel lbl_r_mfd_amount;
    private javax.swing.JLabel lbl_r_subtotal;
    private javax.swing.JLabel lbl_r_tax;
    private javax.swing.JLabel lbl_r_total;
    private javax.swing.JLabel lbl_recipt;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_tax;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel pan_head;
    private javax.swing.JPanel pan_l1;
    private javax.swing.JPanel pan_l2;
    private javax.swing.JPanel pan_r1;
    private javax.swing.JPanel pan_r2;
    private javax.swing.JPanel pan_recipt;
    private javax.swing.JPanel pan_total;
    private javax.swing.JTextField tf_cd;
    private javax.swing.JTextField tf_cf;
    private javax.swing.JTextField tf_ct;
    private javax.swing.JTextField tf_d_cofee;
    private javax.swing.JTextField tf_d_lemonade;
    private javax.swing.JTextField tf_d_milk;
    private javax.swing.JTextField tf_d_tea;
    private javax.swing.JTextField tf_f_dosa;
    private javax.swing.JTextField tf_f_noodle;
    private javax.swing.JTextField tf_f_paav;
    private javax.swing.JTextField tf_f_vada;
    private javax.swing.JTextField tf_subtotal;
    private javax.swing.JTextField tf_tax;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
